### ISSUE TITLE
`eq` not filtered out when adding methods

### ISSUE THREAD

**Issue by felixmulder** [felixmulder/dotty#20]
When getting the defs from an implicitly added conversion, `eq` methods are not filtered out by:

``` scala
val defs = sym.info.membersBasedOnFlags(Flags.Method, Flags.Synthetic | Flags.Private).map { meth =>
  track(meth.symbol, ctx) {
    DefImpl(meth.symbol.name.decode.toString, Nil, path(meth.symbol), returnType(meth.info), typeParams(meth.symbol), paramLists(meth.symbol))
  }
}.toList
```

ping: @DarkDimius

**Comment by DarkDimius** [comment]
I think you'll need to decide what to do with methods inherited from Any & AnyRef. I'd say you shouldn't show `final` methods defined in either `Any` or `AnyRef`. This would also cover `notify` & friends.

btw: `meth.symbol.name.decode.toString` -> `meth.symbol.name.show`

**Comment by felixmulder** [comment]
Great, thanks!
